using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PatientAccess.Data.Entities;

namespace PatientAccess.Data.Configurations;

internal sealed class AIPromptLogConfiguration : IEntityTypeConfiguration<AIPromptLog>
{
    public void Configure(EntityTypeBuilder<AIPromptLog> builder)
    {
        builder.ToTable("ai_prompt_log");
        builder.HasKey(a => a.Id);

        // UUID generated by Postgres — avoids sequential GUID fragmentation (DR-003)
        builder.Property(a => a.Id)
            .HasDefaultValueSql("gen_random_uuid()");

        builder.Property(a => a.Timestamp)
            .IsRequired()
            .HasDefaultValueSql("NOW()");

        builder.Property(a => a.ModelProvider)
            .HasMaxLength(50)
            .IsRequired();

        builder.Property(a => a.DeploymentName)
            .HasMaxLength(100)
            .IsRequired();

        // Metadata only — no PHI. 500 chars is generous for "turns:N est_tokens:N" format.
        builder.Property(a => a.RequestSummary)
            .HasMaxLength(500)
            .IsRequired();

        builder.Property(a => a.ResponseSummary)
            .HasMaxLength(500)
            .IsRequired();

        builder.Property(a => a.IsComplete)
            .IsRequired();
    }
}
